name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd headless_wrapper
          docker compose down
          docker compose up -d --build
          docker image prune -f
